from LinkedList import *
mylist = LinkedList()
mylist.addHead(5)
mylist.addHead(35)
mylist.addHead(15)
mylist.addHead(25)
mylist.addHead(1)
mylist.addHead(5)
mylist.addHead(15)
mylist.addTail(5)
mylist.traverse()
print()
mylist.addTail(1)
mylist.addTail(35)
mylist.addTail(10)
mylist.traverse()
# print("danh sach co %d Node"%mylist.size())
# pos=5
# print("\nNoi dung cua node thu %d la %d"%(pos,mylist.getNode(pos).info))
# mylist.insrertAt(999,1)
# print("\nSanh sach sau khi insert")
# mylist.traverse()
# print("\nGia tri max cua ds la: %d"%mylist.findMin())
print("\nVi tri cua node co gia tri = 5 thu 2 la: %d"%mylist.findx(5,20))
print()
max=mylist.findMax()
pos=mylist.findx(max,1)
mylist.insrertAt(888,pos+1)
mylist.insrertAt(888,pos)
mylist.traverse()
print("\nSau khi xoa")
mylist.removeAt(mylist.size()-1)
mylist.traverse()

node1=mylist.getNode(200)
node2=mylist.getNode(4)
print("\nAfter swap")
mylist.swap(node1,node2)
mylist.traverse()
print("\nAfer sort")
mylist.sort(mylist.head,mylist.tail)
mylist.traverse()

pos=mylist.findLastMin()
print("\nPos = %d"%pos)


